### ISSUE TITLE
Bug when trying to add profile images

### ISSUE THREAD

**Issue by bartekpacia** [JBossOutreach/visiting-card-android#200]
#### This issue is about [bug/enhancement] 

- [x] Issue Title is in form `Bug/Enhancement: Name`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Bug/Enhancement is worth adding to this repository.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

**Actual Behaviour**

The app simply crashes when clicking the image in the activity where you can see your visiting card.

**Expected Behaviour**

User should be able to normally select profile image.

**Steps to reproduce it**

Try to select profile image.

**LogCat for the issue**

```

2018-12-10 19:18:26.753 26504-26504/com.community.jboss.visitingcard D/AndroidRuntime: Shutting down VM

2018-12-10 19:18:26.755 26504-26504/com.community.jboss.visitingcard E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.community.jboss.visitingcard, PID: 26504
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.community.jboss.visitingcard/siclo.com.ezphotopicker.ui.PhotoIntentHelperActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
        at android.os.Parcel.readException(Parcel.java:1975)
        at android.os.Parcel.readException(Parcel.java:1913)
        at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:6204)
        at android.app.Activity.setRequestedOrientation(Activity.java:5840)
        at siclo.com.ezphotopicker.ui.PhotoIntentHelperActivity.onCreate(PhotoIntentHelperActivity.java:56)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Would you like to work on the issue?**

Currently I don't have time as I'm doing my last GCI task, but after GCI - why not 😀 . If nobody fixes it, I will.

**System Specifications**
  - System: Android 8.0 Oreo

```
Device: SM-G960F (starltexx, samsung)
Android version: 8.0.0
Android build: R16NW.G960FXXS2BRJ6
c:geo version: 2018.10.13
Google Play services: enabled - 14.7.99 (040408-223214910)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: pl_PL
System date format: dd.MM.y
Debug mode active: no
```

**Comment by abbhinay** [comment]
I think crashing of app has something to do with the "targetSdkVersion 28". It worked just fine when i changed this to 26.
